# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='film_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('picture', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.AlterField(
            model_name='maoyan',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
