# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0002_auto_20180729_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmCritics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[(0, '爱情'), (1, '剧情'), (2, '科幻'), (None, '请选择电影类型')], max_length=10)),
                ('visits', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MoviesInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(default='imgs/default_poster.png', upload_to='poster')),
                ('name', models.CharField(max_length=30)),
                ('actor', models.CharField(max_length=100)),
                ('score', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('tel', models.IntegerField()),
                ('passwd', models.CharField(max_length=14)),
                ('avator', models.ImageField(default='imgs/default_avator.png', upload_to='avator')),
            ],
        ),
        migrations.DeleteModel(
            name='film_info',
        ),
        migrations.DeleteModel(
            name='maoyan',
        ),
    ]
