# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-08 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0003_auto_20180731_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth', models.CharField(max_length=20, verbose_name='作者')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='影评名')),
                ('visits', models.IntegerField(default=0, verbose_name='浏览量')),
                ('content', models.TextField(verbose_name='影评内容')),
                ('zan', models.IntegerField(default=0, verbose_name='点赞量')),
            ],
            options={
                'verbose_name': '影评信息',
                'verbose_name_plural': '影评信息',
                'ordering': ['zan'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=128, verbose_name='标签名')),
            ],
            options={
                'verbose_name': '分类标签',
                'verbose_name_plural': '分类标签',
            },
        ),
        migrations.DeleteModel(
            name='FilmCritics',
        ),
        migrations.AlterModelOptions(
            name='moviesinfo',
            options={'ordering': ['score'], 'verbose_name': '电影信息', 'verbose_name_plural': '电影信息'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
        migrations.AddField(
            model_name='moviesinfo',
            name='critics_num',
            field=models.IntegerField(default=1, verbose_name='影评数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moviesinfo',
            name='is_notice',
            field=models.BooleanField(default=False, verbose_name='开启轮播'),
        ),
        migrations.AlterField(
            model_name='moviesinfo',
            name='actor',
            field=models.CharField(max_length=100, verbose_name='主演'),
        ),
        migrations.AlterField(
            model_name='moviesinfo',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='影名'),
        ),
        migrations.AlterField(
            model_name='moviesinfo',
            name='poster',
            field=models.ImageField(default='imgs/default_poster.png', upload_to='poster', verbose_name='海报'),
        ),
        migrations.AlterField(
            model_name='moviesinfo',
            name='score',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='豆瓣评分'),
        ),
        migrations.AddField(
            model_name='moviesinfo',
            name='tag',
            field=models.ManyToManyField(max_length=10, related_name='movie_set', to='moviesapp.Tag', verbose_name='分类标签'),
        ),
    ]
