# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-08 06:25
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0004_auto_20180808_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_tag', to='moviesapp.MoviesInfo', verbose_name='对应电影'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moviesinfo',
            name='tag',
            field=models.ManyToManyField(max_length=10, related_name='moviesinfo_set', to='moviesapp.Tag', verbose_name='分类标签'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='影评内容'),
        ),
    ]
