# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-08 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0005_auto_20180808_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesinfo',
            name='poster',
            field=models.ImageField(default='/media/imgs/404.png', upload_to='poster', verbose_name='海报'),
        ),
    ]
