# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0006_auto_20180808_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesinfo',
            name='director',
            field=models.CharField(default=1, max_length=100, verbose_name='导演'),
            preserve_default=False,
        ),
    ]
