# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0007_moviesinfo_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesinfo',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='影名'),
        ),
    ]
