# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0009_auto_20180809_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesinfo',
            name='is_notice',
            field=models.NullBooleanField(default=False, verbose_name='开启轮播'),
        ),
    ]
