# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-11 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0011_auto_20180809_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesinfo',
            name='actor',
            field=models.CharField(max_length=128, verbose_name='主演'),
        ),
        migrations.AlterField(
            model_name='moviesinfo',
            name='director',
            field=models.CharField(max_length=128, verbose_name='导演'),
        ),
        migrations.AlterField(
            model_name='moviesinfo',
            name='score',
            field=models.CharField(max_length=128, verbose_name='豆瓣评分'),
        ),
        migrations.RemoveField(
            model_name='moviesinfo',
            name='tag',
        ),
        migrations.AddField(
            model_name='moviesinfo',
            name='tag',
            field=models.CharField(default=1, max_length=128, verbose_name='分类标签'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviews',
            name='auth',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='movie',
            field=models.CharField(max_length=128, verbose_name='对应电影'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='visits',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='浏览量'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='zan',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='点赞量'),
        ),
    ]
