# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0019_auto_20180812_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviesinfo',
            name='tag',
        ),
        migrations.AddField(
            model_name='moviesinfo',
            name='tag_char',
            field=models.CharField(default=1, max_length=128, verbose_name='分类标签名字'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moviesinfo',
            name='tag_for',
            field=models.ManyToManyField(max_length=10, related_name='moviesinfo_set', to='moviesapp.Tag', verbose_name='分类标签外键'),
        ),
    ]
