# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0021_auto_20180812_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesinfo',
            name='actor',
            field=models.CharField(max_length=256, verbose_name='主演'),
        ),
        migrations.AlterField(
            model_name='moviesinfo',
            name='director',
            field=models.CharField(max_length=256, verbose_name='导演'),
        ),
        migrations.AlterField(
            model_name='moviesinfo',
            name='score',
            field=models.CharField(max_length=256, verbose_name='豆瓣评分'),
        ),
        migrations.AlterField(
            model_name='moviesinfo',
            name='tag_char',
            field=models.CharField(max_length=256, verbose_name='分类标签名字'),
        ),
        migrations.AlterField(
            model_name='moviesinfo',
            name='tag_for',
            field=models.ManyToManyField(blank=True, max_length=256, null=True, related_name='moviesinfo_set', to='moviesapp.Tag', verbose_name='分类标签外键'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='auth',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='movie_char',
            field=models.CharField(max_length=256, verbose_name='对应电影名称'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='影评名'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(max_length=256, verbose_name='标签名'),
        ),
    ]
