# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0022_auto_20180812_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesinfo',
            name='poster',
            field=models.ImageField(default='/media/imgs/404.png', upload_to='pics2', verbose_name='海报'),
        ),
    ]
