# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0023_auto_20180812_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avator',
            field=models.ImageField(default='imgs/default_avator.png', upload_to='avator', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='passwd',
            field=models.CharField(max_length=14, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='tel',
            field=models.CharField(max_length=11, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=10, verbose_name='用户名'),
        ),
    ]
