# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0025_auto_20180823_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='passwd',
        ),
    ]
